---
version: 1
disable_existing_loggers: True

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    message_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: message.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

    DeepCalculatorBot:
        level: INFO
        handlers: [console, info_file_handler]

    DeepCalculatorBotMsg:
        level: INFO
        handlers: [message_file_handler]

DeepCalculatorBot:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]

DeepCalculatorBotMsg:
    level: INFO
    handlers: [message_file_handler]